services:
  conway:
    build:
      context: .
    develop:
      watch:
        - path: .
          action: rebuild
    restart: no
    ports:
      - ${HOST_HTTP_PORT}:8080

  postgres:
    restart: no
    ports:
      - ${HOST_DB_PORT}:5432
